@startuml
'https://plantuml.com/sequence-diagram

participant Main
participant TacheComposite
participant ArrayList as "sousTaches:ArrayList"

Main --> TacheComposite : supprimerSousTache(int[])
alt 0<entier<nbSousTaches
activate TacheComposite
TacheComposite --> ArrayList : remove(int[])
activate ArrayList
TacheComposite <-- ArrayList : Tache
deactivate ArrayList
Main <-- TacheComposite : Tache
deactivate TacheComposite
else
Main <-- TacheComposite : IndiceInvalideException
end
@enduml